### PR TITLE
Feat: Add a course functionality added and routing to video page with course_id

### PR DESCRIPTION
**Pull request by yash2324**

### CODE REVIEW

**Comment by thisisamank** [comment]
Screenshot 2024-07-10 at 8 02 42 PM
please fix the inconsistent height of the cards.

**Comment by thisisamank** [comment]
also @yash2324  please implement `DELETE /course/:id` feature when the user taps on these
Screenshot 2024-07-10 at 8 05 05 PM

**Comment by yash2324** [comment]
> also @yash2324 please implement `DELETE /course/:id` feature when the user taps on these Screenshot 2024-07-10 at 8 05 05 PM

Ok bhaiya doing

**Review by thisisamank — CHANGES_REQUESTED** [review]
apart from the comments, LGTM

**Review by thisisamank — APPROVED** [review]

**Pull request merged**
